import pandas as pd

from bop_twin.criteria.pressure_acceptance_v2 import PressureTestSpec, evaluate_pressure_test
from bop_twin.io.load_config import load_config


def main():
    # CSV generated by examples/run_ns47.py
    df = pd.read_csv("out/ns47_mvp.csv")
    cfg = load_config("configs/ns47.json", convert_to_SI=False)

    time_array = df["t_s"].to_numpy()
    pressure_array = df["P_acc_pa"].to_numpy()  # signal in Pa

    rwp_psi = float(cfg["meta"].get("bop_class_pressure_psi", 15000.0))
    fluid_rho = float(cfg["fluid"].get("rho", 1060.0))
    lda_m = float(cfg["meta"].get("water_depth_contract_m", 0.0))

    spec = PressureTestSpec(
        mode="high",
        require_rwp_stabilization_rule=True,
        check_measured_bop_pressure=True,
    )

    result = evaluate_pressure_test(
        time_array,
        pressure_array,
        spec,
        designated_pressure_psi=3000.0,  # example
        rwp_psi=rwp_psi,
        pressure_unit="pa",
        high_test_justified_below_min=False,
        bop_nominal_pressure_psi=rwp_psi,
        fluid_density_kg_m3=fluid_rho,
        lda_m=lda_m,
    )

    if result.ok:
        print("TEST APPROVED:", result.reason)
    else:
        print("TEST FAILED:", result.reason)
        print("Details:", result.details)


if __name__ == "__main__":
    main()
